config/routes.rb
Rails.application.routes.draw do

  resources :restaurants, only: [ :index, :new, :create, :show ] do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"]}

  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, :numericality => true # returns 0 not nil
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def show
    set_res
  end

  private

  def set_res
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_res

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save # this line will (1) check AND (2) save if valid!
      redirect_to restaurant_path(@restaurant)
    else
      render :new # if invalid, then retain entered information on the page
    end
  end

  private

  def set_res
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurant List </h1>
<%= link_to "Click here to add a new restaurant", "/restaurants/new" %>
<hr>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Cuisine</th>
      <th>Phone Number</th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |res| %>
      <tr>
        <td><%= link_to res.name.capitalize, restaurant_path(res) %>
        </td>
        <td>
          <p> <%= res.address %> </p>
        </td>
        <td><%= res.category.capitalize %></td>
        <td><%= res.phone_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/new.html.erb
<h1>Add a New Restauarnt </h1>
<%= simple_form_for(@restaurant) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category %>
    <%= f.input :phone_number %>
  </div>
  <div class="form-actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/restaurants/show.html.erb
<h1>Restaurant List </h1>
<%= link_to "Click here to return to home page", restaurants_path %>
<h2>Restaurant Name: @restaurant.name.Capitalize </h2>
<ul>
  <p> Address :   <%= @restaurant.address %> </p>
  <p> Cuisine :   <%= @restaurant.category.capitalize %> </p>
  <p> Phone No.:  <%= @restaurant.phone_number %> </p>
  <p> Review: </p>
  <% @restaurant.reviews.each do |review| %>
    <ul>
      <li> Rating: <%= review.rating %> </li>
      <li> Comments: <%= review.content %> </li>
    </ul>
  <% end %>
</ul>
<%= link_to "Add a review", new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>Restaurant List</h1>
<h2>Restaurant Name: <%= @restaurant.name.capitalize %> </h2>
<ul>
  <p> Address :   <%= @restaurant.address %> </p>
  <p> Cuisine :   <%= @restaurant.category.capitalize %> </p>
  <p> Phone No.:  <%= @restaurant.phone_number %> </p>
  <p> Reviews: </p>
  <% @restaurant.reviews.each do |review| %>
    <ul>
      <li> Rating: <%= review.rating %> </li>
      <li> Comments: <%= review.content %> </li>
    </ul>
  <% end %>
</ul>
<h2>Please enter your feedback below:</h2>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content, class: 'form-control' %>
  <%= f.label :rating %>
  <%= f.text_field :rating, class: 'form-control' %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>